<div class="licence">
<span>Licence CC BY-NC-ND</span>
<span>Valérie Roy</span>
<span><img src="media/ensmp-25-alpha.png" /></span>
</div>

In [1]:
import numpy as np

# multi-dimensional arrays

   - for now we have only created **flat** arrays like **vectors**
   - **but** with *numpy* you can create **multi-dimensional** arrays like **matrices**
   

   - for **multi-dimensional** arrays the underlying memory space is **still** a one-dimensional segment
   - **but** it is viewed as a **multi-dimensional array**  

## shape of an array
   - with the function *numpy.ndarray.shape*

we **initialize** the *numpy.ndarray* with a **flat** structure

In [2]:
a = np.array([1, 2, 3, 4, 5, 6], np.int32)
a

array([1, 2, 3, 4, 5, 6], dtype=int32)

we can see that its **shape** is a **one**-dimentional array

In [3]:
a.shape

(6,)

## creation of multi-dimensional arrays
   - with the *function* *numpy.array*

we create a *2 x 3* matrix
   - by *initializing* the array with a **structured** array
   - here a list of the two **rows** of the matrix

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]], np.int32)  # a (2 x 3) arrays of 32-bits integers
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

its shape is *2 x 3* (two *rows*, 3 *columns*)

In [5]:
a.shape

(2, 3)

## methods to create arrays in *numpy* 

| methods                    | what they do                           	|
|---------------------------|-------------------------------------------|
| *numpy.array*  	| create an array                           |
| *numpy.empty*  	| return an empty without initializing its elements |
| *numpy.zeros*  	| return an array filled with $0.$ (float)  |
| *numpy.ones*  	| return an array filled with $1.$ (float)  |
| *numpy.linspace* | floats spaced evenly within on an interval |
| *numpy.arange*   | integers spaced  evenly on an interval   |
| *numpy.random.** | random sampling                           |
| *numpy.logspace* | return numbers spaced evenly on a log scale  |

## creating empty arrays

you have to give the **shape** of the array (with the eponym parameter)

an array of shape *3 lines x 2 columns*
   - **without** initialisation

In [6]:
e = np.empty(shape=(2, 3))
e

array([[4.65973828e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

   - but **not** without values !
   - a memory place has **always** a value
   - but you have **avoided** the **cost** of initialisation

## creating zeros or ones-initialized arrays

a *(3 x 4)* matrix of 32-bits integers initialized with *1*

In [7]:
np.ones(shape=(3, 4), dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

a *(4 x 5)* matrix initialized with *1*

In [8]:
z = np.zeros(shape=(4, 5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
z.dtype

dtype('float64')

## dimensions

a **shape = (n, )** shaped array is **not** a **multi-dimensional** array

In [10]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [11]:
a.shape

(3,)

a **shape = (n, p)** shaped array is a **multi-dimensional** array

In [12]:
b = np.array( [[1, 2, 3]] )
b

array([[1, 2, 3]])

In [13]:
b.shape

(1, 3)

## as many dimensions as you want

we create a structure of:
   - *two* times, *three* blocks
   - of *four* matrices
   - having *five* rows and *six* columns
   

In [14]:
d = np.ones(shape=(2, 3, 4, 5, 6))
d.shape

(2, 3, 4, 5, 6)

the two lasts are *always* **rows** and **columns**

**very difficult to see on a slide ...**

In [15]:
# np.ones(shape=(2, 3, 4, 2, 2))  # 2 times, 3 blocks, 4 matrices, of size (2 x 2)

## initialising arrays with random numbers
   - lots of functions *numpy.random.rand*, *numpy.random.randint*, *numpy.random.randn*

we generate
   - *2* matrices of *3* rows and *4* columns
   - of 8-bits integers **randomly** generated between *1* and *100*

In [16]:
nmin, nmax = 1, 100
np.random.randint(nmin, nmax, size=(2, 3, 4), dtype=np.int8) # nmin included, nmax excluded

array([[[17, 31, 91, 57],
        [43, 34, 91, 22],
        [97, 50, 71,  1]],

       [[13, 34, 75, 34],
        [55, 77, 11, 82],
        [58, 77, 91, 12]]], dtype=int8)

### ask for help !

In [17]:
# np.random.randint?

In [18]:
# help(np.random.randint)

## generating a normal distribution of $\mathcal{N(\mu, \sigma^2)}$
   - with *numpy.random.randn* 

we generates random samples from a *standard normal distribution* $\mathcal{N(\mu=0, \sigma^2=1)}$

In [19]:
a = np.random.randn(2, 3)
a

array([[ 1.95307537,  0.94172622, -0.82505696],
       [ 0.51631756,  1.67652078, -1.10828172]])

we generates a normal distribution $\mathcal{N(\mu=2.5, \sigma^2=0.09)}$

In [20]:
sigma = 0.03
mu = 2.5

sigma * a + mu

array([[2.55859226, 2.52825179, 2.47524829],
       [2.51548953, 2.55029562, 2.46675155]])

In [21]:
# the same for short
np.random.normal(mu, sigma, size=(2, 3))

array([[2.50052398, 2.55803212, 2.46186634],
       [2.53412641, 2.53751878, 2.48538036]])

##  reshaping *numpy.ndarray*
   - with the method *numpy.ndarray.reshape*

In [22]:
a = np.array([1, 2, 3, 4])
b = a.reshape(2, 2)
b

array([[1, 2],
       [3, 4]])

   - it changes the **shape** of an array (even a multi-dimensional one)
   - by creating a **new view** with a **new indexing**
   - it does not change the **original underlying** array   
   - **no** underlying array is generated only **indexes** are    
   - the **resulting** array and the **original** one have the **same** underlying memory array

### dimension must match
   - the dimension must be a multiple of the number of elements

In [23]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b1 = a.reshape(2, 6)
b2 = b1.reshape(2, 2, 3)
b3 = b2.reshape(1, 1, 3, 4)

In [24]:
b2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
b3

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

*b1* is a **view** on *a*, *b2* is a **view** on *b1* and *b3* is a **view** on *b2*

## accessing elements
   - depends on the **geometry** of the views

In [26]:
a[0] = 99 # we change a

In [27]:
b1[0][0] # it changes b1

99

In [28]:
b2[0][0][0] # it changes b2

99

In [29]:
b3[0][0][0][0] # it changes b3

99

## flattening an array with *numpy.ravel* 
   - it returns a **view** on the **original data** (when possible)

In [30]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
a_ravel = a.ravel()

   - if we modify **a_ravel**
   - **a** will be modified

In [32]:
a[0][0] = 99; a_ravel[0]

99

## flattening an array with *numpy.ndarray.flatten* 
   - it always returns a **copy** of the **original data**

In [33]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a_flatten = a.flatten()

   - if we modify **a_flatten**
   - **a** will **not** be modified

In [35]:
a_flatten[2] = 111 ; a[1][0]

3

## iteration on a flattened version of the array 
   - *numpy.ndarray.flat* returns a flat **iterator** over the array

In [36]:
a = np.random.randint(0, 20, 6).reshape(2, 3)
a

array([[ 5,  8, 14],
       [15,  6, 12]])

In [37]:
a[1][2] == a.flat[3]

False

### example
   - we get the index of the **minimum**
   - (function *numpy.ndarray.argmin* i.e. argument of the min)
   - we obtain an **index** on the **flat** array
   - we use the **flat iter** to get the element

In [38]:
a.min(), a.argmin()

(5, 0)

In [39]:
a.flat[  a.argmin()  ] == a.min()

True

## resizing an array with the method *ndarray.resize*

   - it change the shape of an array **in-place**
   - i.e. the indexing of the **original array** is **changed**

   - we have the same restriction as for the reshaping
   - the new **dimension** must **match** the number of elements of the **original array**

In [40]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a.shape

(12,)

In [41]:
a.resize(2, 2, 3)  # indexes of a are modified

In [42]:
a.shape

(2, 2, 3)

In [43]:
a.resize(2, 6) # indexes of a are modified
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [44]:
a.shape

(2, 6)

## repeating elements of an array to create a new one

In [45]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

we **repeat** each element *3* times and return a **flattened** array

In [46]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

## axes of an array

two **axes**: **rows** (indice *0*) and  **columns** (indice *1*)

In [47]:
a = np.random.randint(0, 20, 12).reshape(3, 4)
a

array([[ 8, 18, 15,  3],
       [ 2, 19,  4,  0],
       [ 4,  7,  0,  0]])

three **axes**:
   - **blocks** (indice *0*)
   - **rows** (indice *1*)
   - **columns** (indice *2*

In [48]:
a = np.random.randint(0, 20, 12).reshape(2, 2, 3)
a

array([[[19, 15,  1],
        [10, 10,  6]],

       [[ 6, 17,  6],
        [ 5,  9,  6]]])

## repeating along an axis of the array 1/2

In [49]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

**axis 0** we repeat the **rows**

**axis 1** we repeat the **columns**

In [50]:
# repeating each row 2 times
np.repeat(a, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [51]:
# repeating the first column 2 times
#           the second column 3 times
np.repeat(a, (2, 3), axis=1)

array([[1, 1, 2, 2, 2],
       [3, 3, 4, 4, 4]])

## repeating along an axis of the array 2/2

In [52]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(2, 2, 3)
a # we have two blocks of 2 rows and 3 columns

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
# we repeat each block 2 times
np.repeat(a, 2, axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
# we repeat first block 2 times
#           second block 1 times 
np.repeat(a, (2, 1), axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## tiling an array with the function *numpy.tile*

In [55]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

we tile the array
   - 2 times in column axis

In [56]:
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

---

we tile the array
   - 2 times in row axis
   - 3 times in column axis

In [57]:
np.tile(a, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

## concatenating arrays with the method *numpy.ndarray.concatenate*

   - it **returns** a **new** object of type *numpy.ndarray*

In [58]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])
b = np.array([[10, 20, 30],
              [40, 50, 60]])

you concatenate along an **axis**, in a 2-dimensional array:
   - rows are **added** on top of each other ($0$ is for **rows**)
   - columns are **added** after each other ($1$ is for **columns**)

In [59]:
np.concatenate((a, b), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [60]:
np.concatenate((a, b), axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

## stacking  python arrays along an axis with the function *numpy.stack*
   - you **join** a sequence of **arrays** along an **axis**

In [61]:
a = [0, 2, 3,], [5, 6, 7], [8, 9, 10]

**axis 0**: sub-arrays became rows 

In [62]:
np.stack(a, axis = 0)

array([[ 0,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

**axis 1** : sub-arrays became columns

In [63]:
np.stack(a, axis = 1)

array([[ 0,  5,  8],
       [ 2,  6,  9],
       [ 3,  7, 10]])

   - see also *np.dstack*, *np.hstack*, *np.vstack*, *numpy.column_stack*

## **concatenation** in higher dimensions (a full example) [1/4]

we create two *numpy.ndarray* *a* and *b*, each having *2* groups of *3* matrices of *4* rows and *5* columns

In [64]:
a = np.array(np.arange(0, 240, 2)) # even numbers from 0 to 238
a.resize(2, 3, 4, 5)               # 2 groups of 3 matrix of 4 rows and 5 columns

In [65]:
b = np.array(np.arange(1, 241, 2)) # odd numbers from 1 to 249
b.resize(2, 3, 4, 5)               # 2 groups of 3 matrix of 4 rows and 5 columns

### **concatenation** along axis $0$ [2/4]
   - we stacking the $2$ times ($3$ matrices of size $4 \times 5$ of the two arrays)
   - i.e. we obtain $4$ times $3$ matrices of size $4 \times 5$

In [66]:
c = np.concatenate((a, b), axis=0)
c.shape

(4, 3, 4, 5)

   - $c[0]$ is $a[0]$
   - $c[1]$ is $a[1]$
   - $c[2]$ is $b[0]$
   - $c[3]$ is $b[1]$

In [67]:
np.all( c[0] == a[0] )   # we compare arrays we obtain an array of booleans
                         # we check if all elements are true

True

### **concatenation** of *a* and *b* **along** axis $1$ [3/4]
   - it is like stacking the $3$ matrices of size $4 \times 5$ of the two arrays
   - i.e. we obtain $2$ times $6$ matrices of size $4 \times 5$
      - the three first matrices come from *a* (even numbers)
      - the three other matrices come from *b* (odd numbers)

In [68]:
d = np.concatenate((a, b), axis=1)
d.shape

(2, 6, 4, 5)

### **concatenation** of *a* and *b* **along** axis $2$ [4/4]
   - in our example, it is like **stacking** the rows of the matrices ($4 \times 5$)
   - i.e. we obtain $2$ times $3$ matrices of size $8 \times 5$
      - the first four rows of the matrices come from *a* (even numbers)
      - the other rows come from *b* (odd numbers)
            
   - same for last **axis** $3$

In [69]:
d = np.concatenate((a, b), axis=2)
d.shape

(2, 3, 8, 5)

## spliting arrays with the method *numpy.ndarray.split*

   - You split along a dimension i.e. along an **axis**
   - for 2-dimensional arrays ($0$ is for **rows**, $1$ is for **columns**)

   - an array of $30$ elements between $0$ and $30$
   - is created with a **shape** $(30, )$ using the function *nyumpy.arange*
   - and **reshaped** to a $5 \times 6$ matrix

In [70]:
a = np.array(np.arange(1, 31)).reshape((5, 6)) # one 5 x 6 matrix of 64-bits integers
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [71]:
a.dtype, a.shape

(dtype('int64'), (5, 6))

to **split**
   - you indicate the way to split: integer or sub-arrays
   - and the **axis** to split

**split** giving an integer $n$:
   - it splits along the **axis** in two sub-arrays
   - the first array contains the $n$ elements (if possible)
   - the last sub-array contains what remains
   - the last sub-array can be empty

   
   
   
   - if the index exceeds the shape
   - a partial sub-array is returned

In [72]:
np.split(a, [3]) # in axis 0 by default (rows)
                 # you split in two sub-arrays
                 #   - the first is a 3 x 6 sub-array
                 #   - the second is a 2 x 6 partial sub-array

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]])]

In [73]:
np.split(a, [6]) # the first sub-array is the 5 x 6 array
                 # the second sub-array is an empty-array

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]), array([], shape=(0, 6), dtype=int64)]

In [74]:
np.split(a, [10]) # the first sub-array is the 5 x 6 array
                  # the second sub-array is an empty-array

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]), array([], shape=(0, 6), dtype=int64)]

In [75]:
np.split(a, [3], axis=1) # the first sub-array contains the 3 columns
                         # the second the 3 others

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21],
        [25, 26, 27]]), array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24],
        [28, 29, 30]])]

In [76]:
np.split(a, [6], axis=1) # the first sub-array contains the 3 columns
                         # the second is empty

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]), array([], shape=(5, 0), dtype=int64)]

**split** giving an **section**:
   - you indicate along which **axis** the array must be split
   - and you indicate the sections
   - e.g. **[p, q]** in **axis 0** results in:
      - the **first** **p** elements of the axis
      - then the elements from **p** to **q** (**q** is not included)
      - then the elements from **q** to the end

In [77]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [78]:
np.split(a, [2, 4], axis=0) # the 2 first rows (indices 0 and 1)
                            # then the rows from indice 2 to 4 not included (indice 3 and 4)
                            # then the last row (indice 4)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30]])]

In [79]:
a1, a2, a3 = np.split(a, [2, 5], axis=1) # the two first columns
                                         # then the columns from 2 to 5 (not included)
                                         # then the last column

In [80]:
a1.shape, a2.shape, a3.shape

((5, 2), (5, 3), (5, 1))

#### spliting in higher dimensions

In [81]:
a = np.array(np.arange(1, 61)).reshape((2, 5, 6)) # 2 arrays of 5 x 6 matrix
a

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]]])

along **axis 0**
   - i have two matrices of shape $5 \times 6$

In [82]:
np.split(a, [1], axis=0) # i split the axis 0 in two, one matrix in each sub-array

[array([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29, 30]]]), array([[[31, 32, 33, 34, 35, 36],
         [37, 38, 39, 40, 41, 42],
         [43, 44, 45, 46, 47, 48],
         [49, 50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59, 60]]])]

along **axis 1** (rows of the matrices)

In [83]:
a

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]]])

In [84]:
a1, a2 = np.split(a, [2], axis=1) # we obtain two sub-arrays
                                  # they have each:
                                  #    - two times one array of size 2 x six (the [2])
                                  # the first has two matrices with the first 2 rows (as requested by [2])
                                  # the second has the remaining three rows

In [85]:
a1

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42]]])

In [86]:
a2

array([[[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]],

       [[43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]]])

In [87]:
a1.shape, a2.shape

((2, 2, 6), (2, 3, 6))

In [88]:
a1, a2

(array([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]],
 
        [[31, 32, 33, 34, 35, 36],
         [37, 38, 39, 40, 41, 42]]]), array([[[13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29, 30]],
 
        [[43, 44, 45, 46, 47, 48],
         [49, 50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59, 60]]]))

## 8) deleting elements, rows and columns

   - **delete** return a new array

In [89]:
a = np.arange(0, 12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

   - deleting **rows**

In [90]:
np.delete(a, [0], axis=0)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

   - deleting **column** 

In [91]:
np.delete(a, [0, 3], axis=1)

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

   - deleting **elements**

In [92]:
np.delete(a, [0, 6, 11])

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10])

In [93]:
x.put?

Object `x.put` not found.


## XXX) sorting an array 

   - *numpy.sort* returns a **copy** of the array
   - *numpy.ndarray.sort* sorts the array **in place**
      
   - you sort along an **axis**

In [94]:
a = np.random.randint(0, 10, (3, 4))
a

array([[8, 6, 7, 9],
       [5, 4, 9, 5],
       [3, 5, 0, 2]])

   - we can sort in the **axis** of the **column**
   - i.e. the **columns** will be sorted for each **row**
   - i.e. **row** will end-up **sorted**

In [95]:
np.sort(a, axis=1)  # a.sort() will modify a in place

array([[6, 7, 8, 9],
       [4, 5, 5, 9],
       [0, 2, 3, 5]])

  - we can sort along the **axis** of the **rows**