<div class="licence">
<span>Licence CC BY-NC-ND</span>
<span>Valérie Roy</span>
<span><img src="media/ensmp-25-alpha.png" /></span>
</div>

In [1]:
import numpy as np

# linear algebra

   - with *numpy* you **manipulate** **vectors** and **matrices**
   - https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

## multiplying two vectors with *numpy.dot*
   - **inner product** of vectors

In [134]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

In [135]:
np.dot(v, w)

32

In [136]:
v.dot(w)

32

*numpy.dot* is for vector and matrix multiplication  
see https://stackoverflow.com/questions/3890621/how-does-multiplication-differ-for-numpy-matrix-vs-array-classes

## multiplying a matrix by a vector  with *numpy.dot*

we create a **matrix**

In [144]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

we create a **vector**

In [145]:
b = np.arange(11, 14).reshape(3, 1)
b

array([[11],
       [12],
       [13]])

In [146]:
np.dot(a, b)

array([[ 74],
       [182]])

In [143]:
# another way to do the same
a.dot(b)

array([[ 74],
       [182]])

## * is for element-by-element multiplication

In [71]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

element-by-element **matrix multiplication**

In [58]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [59]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

element-by-element **vector multiplication**

In [60]:
v*w

array([ 4, 10, 18])

## multiplying matrices

In [63]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
b = np.arange(13, 25).reshape(4, 3)
b

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [67]:
# global numpy function
np.dot(a, b)

array([[190, 200, 210],
       [470, 496, 522],
       [750, 792, 834]])

In [69]:
# or
# numpy.ndarray method
a.dot(b)

array([[190, 200, 210],
       [470, 496, 522],
       [750, 792, 834]])

##  *numpy.vdot*  for the *dot product* of two vectors
   - it should **only** be used for **vectors**
   - it handles **multidimensional** arrays
   - by **flattening** its **input**

In [147]:
a = np.arange(1, 13).reshape(4, 3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [148]:
b = np.arange(11, 23).reshape(3, 4)
b

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [76]:
print(np.vdot(a, b))

1430


   - to obtain the same with *numpy.dot*
   -you must **flatten** the matrices

In [ ]:
np.dot(a.flatten(), b.flatten())

see also *numpy.tensordot*, *numpy.inner*, *numpy.outer*, ...

## matrix multiplication with *numpy.matmul*

In [ ]:
np.matmul(a, b)

In [ ]:
b = np.array([[10, 20],
              [30, 40]])
b

*numpy.matmul* return a *numpy.ndarray*

   - in this example *numpy.matmul* and *numpy.dot* return the **same** result

In [ ]:
np.matmul(a, b) == np.dot(a, b)

   - but it not always the same
   - the functions are **different** see the help
   - or see https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication

### matrix transposition

In [154]:
a = np.arange(1, 13).reshape(4, 3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [155]:
a.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [156]:
np.transpose(a)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

### other mathematic functions

| methods           |   behavior |
|-----------------|--------|
| *numpy.linalg.det* | determinant |
| *numpy.linalg.inv* | inversion |
| *numpy.linalg.eig* | eigen values |
| *numpy.linalg..solve* | solving equation system |
| *numpy.eye*       |identity matrix |
| *numpy.diag*      | extract diagonal|
| *numpy.diag*      | build diagonal matrix |
| **...**           | ...|


## norm

In [120]:
a = np.arange(1, 16).reshape(3, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

   - **2-morm**
   - $\displaystyle \left\|{\boldsymbol {x}}\right\|_{2}={\sqrt {x_{1}^{2}+\cdots +x_{n}^{2}}}$ 

In [126]:
np.linalg.norm(a)

35.21363372331802

In [127]:
np.sqrt(np.sum(np.power(a.ravel(), 2)))

35.21363372331802

## norm on axis (rows)

In [157]:
a = np.arange(1, 16).reshape(3, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [158]:
np.linalg.norm(a, axis=0)

array([12.56980509, 14.03566885, 15.55634919, 17.11724277, 18.70828693])

In [159]:
np.sqrt(np.sum(np.power(a, 2), axis=0))

array([12.56980509, 14.03566885, 15.55634919, 17.11724277, 18.70828693])

## norm on columns

In [130]:
a = np.arange(1, 16).reshape(3, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [131]:
np.linalg.norm(a, axis=1)

array([ 7.41619849, 18.16590212, 29.24038303])

In [132]:
np.sqrt(np.sum(np.power(a, 2), axis=1))

array([ 7.41619849, 18.16590212, 29.24038303])

## determinant

In [106]:
b = np.random.random(size=(3, 3))
b

array([[0.84710939, 0.35280323, 0.54366676],
       [0.9140573 , 0.83756552, 0.66640934],
       [0.97445839, 0.06398629, 0.65102604]])

In [107]:
np.linalg.det(b)

0.033020930566343996

## diagonal

In [110]:
b = np.random.random(size=(3, 3))
b

array([[0.25662501, 0.53706869, 0.88564575],
       [0.31300225, 0.58970023, 0.07713275],
       [0.6128746 , 0.10784074, 0.22688711]])

returns the diagonal

In [109]:
np.diag(b) 

array([0.59601918, 0.82013771, 0.57668624])

creates a diagonal matrix

In [111]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## trace

   - the sum along the **diagonal** of the arrays

In [103]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
np.trace(b)

15

## inversion

In [93]:
b = np.random.random(size=(3, 3))
b

array([[0.39731894, 0.65464113, 0.36895568],
       [0.72320785, 0.46038022, 0.65640716],
       [0.1711136 , 0.70958816, 0.51409509]])

$b^{-1}b = I$  
rather $b^{-1}b \approx I$ (**almost equal** for computer-numbers) 

In [94]:
np.isclose(  np.dot(np.linalg.inv(b), b),   np.identity(b.shape[0]) )

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## eignen values

   - $f(v) = \lambda v$ 
   - $M v = \lambda v$

In [89]:
M = np.random.random(size=(3, 3))

In [90]:
l, v = np.linalg.eig(M)  # eigen_values, eigen_vectors
l, v

(array([ 1.48831353,  0.11800475, -0.7737042 ]),
 array([[-0.58963432, -0.87569756, -0.49165842],
        [-0.59275895,  0.4800232 , -0.41924037],
        [-0.54860568, -0.05226384,  0.76322311]]))

## eignen values $M v = \lambda v$ and $(M - \lambda I) = 0$

$M v = \lambda v$

In [161]:
np.isclose(   np.dot(M, v[:, 0]),  l[0]* v[:, 0] )

IndexError: too many indices for array

$(M - \lambda I) = 0$

In [92]:
np.isclose(    np.dot(M - l[0]*np.identity(3), v[:, 0]),   np.zeros(3))

array([ True,  True,  True])

## solve

a x = b

In [77]:
A = np.random.random(size=(3, 3))
b = [1, 2, 3]

In [78]:
x = np.linalg.solve(A, b) # A x = b
x

array([ 4.78291535, -1.85250711,  0.17070882])

In [79]:
np.isclose( np.dot(A, x), b)

array([ True,  True,  True])