<div class="licence">
<span>Licence CC BY-NC-ND</span>
<span>Valérie Roy</span>
<span><img src="media/ensmp-25-alpha.png" /></span>
</div>

In [2]:
import numpy as np

# linear algebra

   - with *numpy* you **manipulate** **vectors** and **matrices**
   - https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

## multiplying two vectors with *numpy.dot*
   - for *1-D* arrays: it is **inner product** of vectors
   - $v_{[m]} \times w_{[m]}$

In [29]:
v = np.array([1, 2, 3]); w = np.array([4, 5, 6])
print(v.shape, w.shape)

(3,) (3,)


In [30]:
np.dot(v, w)

32

In [31]:
v.dot(w)

32

## multiplying a matrix by a vector  with *numpy.dot*
   - $A_{[n \times m]} b_{[m]}$

we create a **matrix**

In [59]:
A = np.arange(1, 7).reshape(2, 3)
A.shape

(2, 3)

we create a **vector**

In [60]:
b = np.arange(11, 14)
b.shape

(3,)

In [61]:
np.dot(A, b)

array([ 74, 182])

In [62]:
# another way to do the same
A.dot(b)

array([ 74, 182])

## "*" is for element-by-element multiplication

In [63]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

element-by-element **matrix multiplication**

In [64]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [65]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

element-by-element **vector multiplication**

In [66]:
v*w

array([ 4, 10, 18])

## multiplying matrices with *numpy.dot*

   - for *2-D* arrays *numpy.dot* is **matrix multiplication**

In [67]:
a = np.arange(1, 13).reshape(3, 4)
a.shape

(3, 4)

In [68]:
b = np.arange(13, 25).reshape(4, 3)
b.shape

(4, 3)

In [69]:
# global numpy function
np.dot(a, b)

array([[190, 200, 210],
       [470, 496, 522],
       [750, 792, 834]])

In [70]:
# or
# numpy.ndarray method
a.dot(b)

array([[190, 200, 210],
       [470, 496, 522],
       [750, 792, 834]])

## matrix multiplication with *numpy.matmul*

   - in 2-D *numpy.matmul* and *numpy.dot* return the **same** result
   - (you can use the shortcut *@*)

In [78]:
np.matmul(a, b)

array([[190, 200, 210],
       [470, 496, 522],
       [750, 792, 834]])

In [79]:
a@b

array([[190, 200, 210],
       [470, 496, 522],
       [750, 792, 834]])

In [80]:
np.matmul(a, b) == np.dot(a, b)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [81]:
np.all( np.matmul(a, b) == np.dot(a, b) )

True

## difference between *numpy.matmul* and *numpy.dot*
   - multiplication by scalars is not allowed
   - be careful: in dimension higher than 2-D the behavior of *numpy.matmul* and *numpy.dot* differ

### matrix transposition

In [82]:
a = np.arange(1, 13).reshape(4, 3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
a.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [84]:
np.transpose(a)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

### other mathematic functions

| methods           |   behavior |
|-----------------|--------|
| *numpy.linalg.det* | determinant |
| *numpy.linalg.inv* | inversion |
| *numpy.linalg.eig* | eigen values |
| *numpy.linalg..solve* | solving equation system |
| *numpy.eye*       |identity matrix |
| *numpy.diag*      | extract diagonal|
| *numpy.diag*      | build diagonal matrix |
| **...**           | ...|


## norm

In [92]:
a = np.arange(1, 16).reshape(3, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

   - **2-morm**
   - $\displaystyle \left\|{\boldsymbol {x}}\right\|_{2}={\sqrt {x_{1}^{2}+\cdots +x_{n}^{2}}}$ 

In [96]:
np.linalg.norm(a)

35.21363372331802

In [97]:
np.sqrt(np.sum(np.power(a.ravel(), 2)))

35.21363372331802

## norm on axis (rows)

In [98]:
a = np.arange(1, 16).reshape(3, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [99]:
np.linalg.norm(a, axis=0)

array([12.56980509, 14.03566885, 15.55634919, 17.11724277, 18.70828693])

In [100]:
np.sqrt(np.sum(np.power(a, 2), axis=0))

array([12.56980509, 14.03566885, 15.55634919, 17.11724277, 18.70828693])

## norm on columns

In [101]:
a = np.arange(1, 16).reshape(3, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [102]:
np.linalg.norm(a, axis=1)

array([ 7.41619849, 18.16590212, 29.24038303])

In [103]:
np.sqrt(np.sum(np.power(a, 2), axis=1))

array([ 7.41619849, 18.16590212, 29.24038303])

## determinant

In [104]:
b = np.random.random(size=(3, 3))
b

array([[0.50964617, 0.31420214, 0.96510073],
       [0.06358192, 0.44595809, 0.95935534],
       [0.69994304, 0.38227755, 0.66010813]])

In [105]:
np.linalg.det(b)

-0.11687413613074295

## diagonal

In [106]:
b = np.random.random(size=(3, 3))
b

array([[0.2892109 , 0.0764376 , 0.14581346],
       [0.98995157, 0.33013202, 0.36814805],
       [0.99385876, 0.83248994, 0.98719222]])

returns the diagonal

In [107]:
np.diag(b) 

array([0.2892109 , 0.33013202, 0.98719222])

creates a diagonal matrix

In [108]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## trace

   - the sum along the **diagonal** of the arrays

In [ ]:
b = np.arange(12).reshape(3, 4)
b

In [ ]:
np.trace(b)

## inversion

In [109]:
b = np.random.random(size=(3, 3))
b

array([[0.62108554, 0.49713424, 0.15063209],
       [0.50348508, 0.53210938, 0.12193387],
       [0.75583254, 0.65553891, 0.74183175]])

$b^{-1}b = I$  
rather $b^{-1}b \approx I$ (**almost equal** for computer-numbers) 

In [110]:
np.isclose(  np.dot(np.linalg.inv(b), b),   np.identity(b.shape[0]) )

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## eignen values

   - $f(v) = \lambda v$ 
   - $M v = \lambda v$

In [113]:
M = np.random.random(size=(3, 3))

In [114]:
l, v = np.linalg.eig(M)  # eigen_values, eigen_vectors
l, v

(array([ 1.41140648, -0.16122896, -0.65261992]),
 array([[-0.58614402, -0.87895147,  0.63093704],
        [-0.67977997,  0.30554655, -0.71070635],
        [-0.44083373,  0.36617702,  0.31115099]]))

## eignen values (check that $M v = \lambda v$ and $(M - \lambda I) = 0$)

$M v = \lambda v$

In [116]:
np.isclose(   np.dot(M, v[:, 0]),  l[0]* v[:, 0] )

array([ True,  True,  True])

$(M - \lambda I) = 0$

In [117]:
np.isclose(    np.dot(M - l[0]*np.identity(3), v[:, 0]),   np.zeros(3))

array([ True,  True,  True])

## solve

a x = b

In [118]:
A = np.random.random(size=(3, 3))
b = [1, 2, 3]

In [119]:
x = np.linalg.solve(A, b) # A x = b
x

array([ 2.98051979, -0.17828423,  0.625859  ])

In [120]:
np.isclose( np.dot(A, x), b)

array([ True,  True,  True])